---
title: "mlm"
author: "Pablo Maldonado"
date: "7/11/2024"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(gridExtra)  
library(mnormt) 
library(lme4) 
library(knitr) 
library(kableExtra)
library(tidyverse)
library(ggplot2)
library(viridis)
```


```{r}
granuloma_data <- read.csv("IHC_ISH_clean_data_WIP 1.csv")
```

```{r}
# Fit Poisson GLMs with offset
glm_granuloma <- glm(rep_tb ~ CD4_count_500 + CD8_count_500 + B220_count_500 + Vaccination + Timepoint + offset(log(total_tb)), data = granuloma_data, family = quasipoisson())


summary(glm_granuloma)

# Coefficients from the model
coefficients <- c(Intercept = -2.70185,
                  CD4_count_500 = -0.19521,
                  CD8_count_500 = 0.22937,
                  B220_count_500 = 0.01623,
                  VaccinationSAL = 0.43675,
                  TimepointD56 = 0.79078)

# Function to calculate percentage change
percent_change <- function(coef) {
  (exp(coef) - 1) * 100
}

# Apply the function to all coefficients (excluding the intercept)
percent_changes <- sapply(coefficients[-1], percent_change)

# Output the percent changes
percent_changes
as.data.frame(percent_changes)
```
```{r}
CI <- exp(confint(glm_granuloma))
# Extract coefficients
coefficients <- summary(glm_granuloma)$coef

# Define a significance threshold (e.g., 0.05)
significance_threshold <- 1

# Filter significant coefficients
significant_coefficients <- coefficients[coefficients[, 4] < significance_threshold, ]

# Calculate odds ratios
rate_ratios <- exp(significant_coefficients[, 1])

# Add variable names for interpretation
rate_ratios <- data.frame(
  Rate_Ratio = rate_ratios)



rate_ratios <- as.data.frame(rate_ratios) %>% 
    rownames_to_column('Cell Subset')
CI_df  <- as.data.frame(CI) %>%
    rownames_to_column('Cell Subset')

CI_df <- CI_df %>% dplyr::slice(-1)


rate_ratios <- inner_join(rate_ratios, CI_df, by = "Cell Subset")
rate_ratios$`Cell Subset` <- gsub("^group", "", rate_ratios$`Cell Subset`)
rate_ratios <- rate_ratios  %>%
  filter(`Cell Subset` != "(Intercept)")

rate_ratios 
```

```{r}
rate_ratios<- data.frame(
  Cell_Subset = c("CD4_count_500", "CD8_count_500", "B220_count_500"),
  Rate_Ratio = c(0.8226647, 1.2578057, 1.0163662),
  Lower_CI = c(0.7002648, 1.0319083, 0.9895011),
  Upper_CI = c(0.9656904, 1.5343186, 1.0435044)
)



ggplot(rate_ratios, aes(x = Cell_Subset, y = Rate_Ratio)) +
  geom_point() +
  geom_errorbar(aes(ymin = Lower_CI, ymax = Upper_CI), width = 0.2) +
  coord_flip() +
  theme_minimal() +
  labs(
    x = "Cell Subset",
    y = "Rate Ratio",
    title = ""
  ) +
  theme(
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )

```


```{r}
colnames(granuloma_data)

# Correlation matrix
cor(granuloma_data[, c("RS_prop", "CD4_count_500")])


cor(granuloma_data[, c("RS_prop", "CD8_count_500")])


cor(granuloma_data[, c("RS_prop", "B220_count_500")])
```


```{r fig.height=3, fig.width=8}
# Plot for B220_percent
ggplot(granuloma_data, aes(x = mouse, y = B220_percent, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of B220_percent") +
  xlab("Mouse") +
  ylab("B220_percent") +
  scale_color_viridis_d() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for CD4_percent
ggplot(granuloma_data, aes(x = mouse, y = CD4_percent, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of CD4_percent") +
  xlab("Mouse") +
  ylab("CD4_percent") +
  scale_color_viridis_d() +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for CD8_percent
ggplot(granuloma_data, aes(x = mouse, y = CD8_percent, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of CD8_percent") +
  xlab("Mouse") +
  ylab("CD8_percent") +
  scale_color_viridis_d() +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for Other_percent
ggplot(granuloma_data, aes(x = mouse, y = Other_percent, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of Other_percent") +
  xlab("Mouse") +
  ylab("Other_percent") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for RS_prop
ggplot(granuloma_data, aes(x = mouse, y = RS_prop, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of RS_prop") +
  xlab("Mouse") +
  ylab("RS_prop") +
  scale_color_viridis_d() +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for RS_index
ggplot(granuloma_data, aes(x = mouse, y = RS_index, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of RS_index") +
  xlab("Mouse") +
  ylab("RS_index") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for log_rep_tb
ggplot(granuloma_data, aes(x = mouse, y = log_rep_tb, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of log_rep_tb") +
  xlab("Mouse") +
  ylab("log_rep_tb") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for log_nonrep_tb
ggplot(granuloma_data, aes(x = mouse, y = log_nonrep_tb, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of log_nonrep_tb") +
  xlab("Mouse") +
  ylab("log_nonrep_tb") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for log_total_tb
ggplot(granuloma_data, aes(x = mouse, y = log_total_tb, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of log_total_tb") +
  xlab("Mouse") +
  ylab("log_total_tb") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for log_RS_index
ggplot(granuloma_data, aes(x = mouse, y = log_RS_index, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of log_RS_index") +
  xlab("Mouse") +
  ylab("log_RS_index") +
  scale_color_viridis_d() +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot for log_RS_prop
ggplot(granuloma_data, aes(x = mouse, y = log_RS_prop, color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of log_RS_prop") +
  xlab("Mouse") +
  ylab("log_RS_prop") +
  scale_color_viridis_d() +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = mouse, y = (rep_tb/total_tb), color = lesion)) +
  geom_jitter(width = 0.2) +
  ggtitle("Dotplot of Prop of Replicating Mtb") +
  xlab("Mouse") +
  ylab("Prop of Replicating Mtb") +
  scale_color_viridis_d() +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

# Cell Percentges vs Proportion of Replicating TB
```{r}
#GOOD
ggplot(granuloma_data, aes(x = Other_percent, y = (rep_tb/total_tb), color = lesion)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("Other_percent vs Prop of Replicating Mtb") +
  xlab("Other_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


ggplot(granuloma_data, aes(x = B220_percent, y = (rep_tb/total_tb), color = lesion)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("B220_percent vs Prop of Replicating Mtb") +
  xlab("B220_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = CD8_percent, y = (rep_tb/total_tb), color = lesion)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("CD8_percent vs Prop of Replicating Mtb") +
  xlab("CD8_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = CD4_percent, y = (rep_tb/total_tb), color = lesion)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("CD4_percent vs Prop of Replicating Mtb") +
  xlab("CD4_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
# Each point is a lesion, may come from the same mouse

```{r}
ggplot(granuloma_data, aes(x = CD8_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ Timepoint) +
  ggtitle("CD8_percent vs Prop of Replicating Mtb") +
  xlab("CD8_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = B220_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ Timepoint) +
  ggtitle("B220_percent vs Prop of Replicating Mtb") +
  xlab("B220_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = Other_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ Timepoint) +
  ggtitle("Other_percent vs Prop of Replicating Mtb") +
  xlab("Other_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = CD4_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ Timepoint) +
  ggtitle("CD4_percent vs Prop of Replicating Mtb") +
  xlab("CD4_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# Fecteted by mouse, each dot is a lesion within that mouse
```{r}
#GOOD

ggplot(granuloma_data, aes(x = CD4_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("CD4_percent vs Prop of Replicating Mtb") +
  xlab("CD4_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = CD8_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("CD8_percent vs Prop of Replicating Mtb") +
  xlab("CD8_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = B220_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("B220_percent vs Prop of Replicating Mtb") +
  xlab("B220_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(granuloma_data, aes(x = Other_percent, y = (rep_tb/total_tb), color = Vaccination)) +
  geom_point() +
  facet_wrap(~ mouse) +
  ggtitle("Other_percent vs Prop of Replicating Mtb") +
  xlab("Other_percent") +
  ylab("Prop of Replicating TB") +
  scale_color_viridis_d() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# nb <- glmer.nb(rep_tb ~ CD4_count_500 + CD8_count_500 + B220_count_500 + Vaccination + Timepoint + (1 | mouse/unique_lesion) + offset(log(total_tb)), data = granuloma_data)
# 
# summary(nb)
```


# Lesion nested within mouse
```{r}
model_mouse_offset <- glmer(rep_tb ~ CD4_count_500 + CD8_count_500 + B220_count_500 + 
                              Vaccination + Timepoint + (1 | mouse) + offset(log(total_tb)) + (1 | unique_lesion), 
                            data = granuloma_data, family = poisson())


summary(model_mouse_offset)

# Coefficients from Poisson regression
coefficients <- c(Intercept = -2.75987,
                  CD4_count_500 = -0.09134,
                  CD8_count_500 = 0.06960,
                  B220_count_500 = 0.04841,
                  VaccinationSAL = 0.28365,
                  TimepointD56 = 0.96559)

# Function to calculate percentage change from rate ratio (similar to odds ratio)
percent_change <- function(coef) {
  (exp(coef) - 1) * 100
}

# Apply the function to all coefficients (excluding the intercept)
percent_changes <- sapply(coefficients[-1], percent_change)

# Output the percent changes/outcome rate change. this is like percent change in odds from odds ratios calculated from estimated coefficients
percent_changes

mouse_model_offset_df <- as.data.frame(percent_changes)

mouse_model_offset_df  <- rownames_to_column(mouse_model_offset_df , var = "Cell Subset")



```
 Calculate the rate ratios
```{r echo=TRUE}
CI <- exp(confint(model_mouse_offset))
# Extract coefficients
coefficients <- summary(model_mouse_offset)$coef

# Define a significance threshold (e.g., 0.05)
significance_threshold <- 1

# Filter significant coefficients
significant_coefficients <- coefficients[coefficients[, 4] < significance_threshold, ]

# Calculate odds ratios
rate_ratios <- exp(significant_coefficients[, 1])

# Add variable names for interpretation
rate_ratios <- data.frame(
  Rate_Ratio = rate_ratios)



rate_ratios <- as.data.frame(rate_ratios) %>% 
    rownames_to_column('Cell Subset')
CI_df  <- as.data.frame(CI) %>%
    rownames_to_column('Cell Subset')

CI_df <- CI_df %>% dplyr::slice(-c(1, 2))


rate_ratios <- inner_join(rate_ratios, CI_df, by = "Cell Subset")
rate_ratios$`Cell Subset` <- gsub("^group", "", rate_ratios$`Cell Subset`)
rate_ratios <- rate_ratios  %>%
  filter(`Cell Subset` != "(Intercept)")

rate_ratios 
```


plot rate ratios
```{r echo=TRUE}
rate_ratios <- data.frame(
  Cell_Subset = c("CD4_count_500", "CD8_count_500", "B220_count_500"),
  Rate_Ratio = c(0.9127092, 1.0720808, 1.0496014),
  Lower_CI = c(0.7435882, 0.8485657, 1.0085407),
  Upper_CI = c(1.121988, 1.351081, 1.093222)
)

rate_ratios

ggplot(rate_ratios, aes(x = Cell_Subset, y = Rate_Ratio)) +
  geom_point() +
  geom_errorbar(aes(ymin = Lower_CI, ymax = Upper_CI), width = 0.2) +
  geom_hline(yintercept = 1, linetype = "dotted", color = "red") + # Add dotted line at y = 1
  coord_flip() +
  ylim(0.5, 1.5) +
  scale_y_continuous(breaks = c(0.6, 0.9, 1.2, 1.5)) + # Customize y-axis tick marks
  theme_minimal() +
  labs(
    x = "Cell Subset",
    y = "Rate Ratio",
    title = ""
  ) +
  theme(
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold")
  )



```

```{r}
# For Model 1 (Quasi-Poisson GLM)
deviance_model1 <- deviance(glm_granuloma)

# For Model 2 (Poisson GLMM)
deviance_model2 <- deviance(model_mouse_offset)

# Compare Deviance
deviance_model1
deviance_model2
```




